footprint: [[0.125, 0.15], [0.125, -0.15], [-0.125, -0.15], [-0.125, 0.15]]

obstacle_range: 3
raytrace_range: 0.0

static_layer:
  enabled: true

inflation_layer:
  enabled: true
  inflation_radius: 0.3
  cost_scaling_factor: 10.0

obstacle_layer:
  enabled: true
  track_unknown_space: true
  combination_method: 1

  obstacle_range: 3
  raytrace_range: 0.0

  observation_sources: scan
  scan: {
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }
