TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /map

  acc_lim_x: 8
  acc_lim_theta: 8
  max_vel_x: 0.82
  max_vel_x_backwards: 1
  max_vel_theta: 6
  min_turning_radius: 0.025
  is_footprint_dynamic: true
  footprint_model:
    type: "polygon"
    vertices: [[0.125, 0.15], [0.125, -0.15], [-0.125, -0.15], [-0.125, 0.15]]

  yaw_goal_tolerance: 1
  xy_goal_tolerance: 0.2
  free_goal_vel: false

  dt_ref: 0.2
  dt_hysteresis: 0.1
  min_samples: 3
  free_goals_vel: true
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: -0.1
  max_global_plan_lookahead_dist: 1
  force_reinit_new_goal_dist: 0.7
  feasibility_check_no_poses: 5
  publish_feedback: false
  allow_init_with_backwards_motion: true
  exact_arc_length: false
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 10.0

  min_obstacle_dist: 0.2
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.8
  inflation_dist: 0.23
  include_dynamic_obstacles: false
  legacy_obstacle_association: true
  obstacle_association_force_inclusion_factor: 0.5
  obstacle_association_cutoff_factor: 5
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0
  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.1
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_max_vel_x: 1
  weight_max_vel_theta: 1.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 0.0
  weight_optimaltime: 500.0
  weight_obstacle: 500.0
  weight_viapoint: 1.0
  weight_inflation: 0.1
  weight_adapt_factor: 2.0

  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0
