footprint: [[0.14, 0.17], [0.14, -0.17], [-0.14, -0.17], [-0.14, 0.17]]

obstacle_range: 3
raytrace_range: 3

static_layer:
  enabled: true

inflation_layer:
  enabled: true
  inflation_radius: 0.30
  cost_scaling_factor: 10.0

obstacle_layer:
  enabled: true
  track_unknown_space: true
  combination_method: 1

  obstacle_range: 3
  raytrace_range: 3

  observation_sources: scan
  scan: {
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }
